// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	service2 "bitbucket.org/chattigodev/chattigo-golang-library/pkg/deserializer"
	"bitbucket.org/chattigodev/chattigo-golang-library/pkg/http"
	"bitbucket.org/chattigodev/chattigo-golang-library/pkg/serializer"
	"github.com/castillofranciscodaniel/golang-example/config"
	"github.com/castillofranciscodaniel/golang-example/pkg/client"
	"github.com/castillofranciscodaniel/golang-example/pkg/handler"
	service3 "github.com/castillofranciscodaniel/golang-example/pkg/service"
)

// Injectors from wire.go:

func InitializeServer() config.ContainerServiceImp {
	serializerService := service.NewSerializerServiceImpl()
	deserializerService := service2.NewDeserializerServiceImpl()
	webClient := http.NewWebClientImpl(deserializerService)
	productClient := client.NewProductClientImpl(webClient)
	productService := service3.NewProductServiceIml(productClient)
	healthHandler := handler.NewHealthHandler(serializerService, productService)
	productHandler := handler.NewProductHandler(serializerService, deserializerService, productService)
	containerServiceImp := config.NewContainerServiceImp(healthHandler, productHandler)
	return containerServiceImp
}
