// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	service2 "bitbucket.org/chattigodev/chattigo-golang-library/pkg/deserializer"
	"bitbucket.org/chattigodev/chattigo-golang-library/pkg/http"
	"bitbucket.org/chattigodev/chattigo-golang-library/pkg/serializer"
	"github.com/castillofranciscodaniel/golang-example/config"
	"github.com/castillofranciscodaniel/golang-example/pkg/client"
	"github.com/castillofranciscodaniel/golang-example/pkg/handler"
	service3 "github.com/castillofranciscodaniel/golang-example/pkg/service"
)

// Injectors from wire.go:

func InitializeServer() config.ContainerServiceImp {
	serializerService := service.NewSerializerServiceImpl()
	deserializerService := service2.NewDeserializerServiceImpl()
	webClient := http.NewWebClientImpl(deserializerService)
	messageChannelClient := client.NewMessageChannelClientImpl(webClient)
	messageChannelService := service3.NewMessageChannelServiceIml(messageChannelClient)
	healthHandler := handler.NewHealthHandler(serializerService, messageChannelService)
	messageChannelHandler := handler.NewMessageChannelHandler(serializerService, deserializerService, messageChannelService)
	containerServiceImp := config.NewContainerServiceImp(healthHandler, messageChannelHandler)
	return containerServiceImp
}
