// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	service2 "bitbucket.org/chattigodev/chattigo-golang-library/pkg/deserializer"
	"bitbucket.org/chattigodev/chattigo-golang-library/pkg/serializer"
	"github.com/castillofranciscodaniel/golang-example/config"
	"github.com/castillofranciscodaniel/golang-example/pkg/client"
	"github.com/castillofranciscodaniel/golang-example/pkg/handler"
	service3 "github.com/castillofranciscodaniel/golang-example/pkg/service"
	"github.com/go-resty/resty/v2"
)

// Injectors from wire.go:

func InitializeServer() config.ContainerService {
	restyClient := resty.New()
	serializerService := service.NewSerializerServiceImpl()
	deserializerService := service2.NewDeserializerServiceImpl()
	messageChannelClient := client.NewMessageChannelClientImpl(restyClient, deserializerService)
	messageChannelService := service3.NewMessageChannelServiceIml(messageChannelClient)
	healthHandler := handler.NewHealthHandler(serializerService, messageChannelService)
	messageChannelHandler := handler.NewMessageChannelHandler(serializerService, deserializerService, messageChannelService)
	containerService := config.NewContainerServiceImp(restyClient, healthHandler, messageChannelHandler)
	return containerService
}
